# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
 - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

   static_configs:
    - targets: ['localhost:9090']
 - job_name: 'node_exporter'
   scrape_interval: 15s
   static_configs:
      - targets:
        - '172.17.0.1:9100'

 - job_name: 'consul'
   consul_sd_configs:
      - server: 'finalproject.ops.club:8500'
      - datacenter: 'opsschool-lihi'
   relabel_configs:
      - source_labels: [__meta_consul_tags]
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: ["__address__"]
        target_label: "__address__"
        regex: "(.*):(.*)"
        replacement: "$1:9100"

 - job_name: "node_exporter_kubernetes"
   consul_sd_configs:
      - server: "localhost:8500"
        services:
          - "prom-prometheus-node-exporter-default"
   relabel_configs:
      - source_labels: ["__meta_consul_service_id"]
        replacement: "$1"
        target_label: pod

 - job_name: "consul_metrics"
   consul_sd_configs:
      - server: "localhost:8500"
        services:
          - "consul"
   relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__address__"
        regex: "(.*):(.*)"
        replacement: "$1:8500"
   metrics_path: "/v1/agent/metrics"
   params:
      format: ["prometheus"]