  - hosts: elk_server_elk_true
    remote_user: "ubuntu"
    become: true
    roles:
      - "roles/elk"
    vars_files:
      - "/home/ubuntu/kandula_project/ansible/roles/elk/vars/vars.yml"

  - hosts: ansible_server , elk_server_elk_true
    remote_user: "ubuntu"
    become: true
    roles:
      - "roles/elk_k8s"
    vars_files:
      - "/home/ubuntu/kandula_project/ansible/roles/elk/vars/vars.yml"
